name: Update WAProto

on:
  schedule:
    - cron: "10 1 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-proto:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install packages
        run: |
          yarn
          yarn add protobufjs-cli --dev  # Install protobufjs-cli as a dev dependency
          yarn --pure-lockfile --cwd proto-extract

      - name: Update WAProto.proto
        id: wa_proto_info
        run: |
          yarn --cwd proto-extract start > wa-logs.txt
          WA_VERSION=$(cat wa-logs.txt | perl -n -e'/Current version\: (.+)/ && print $1')
          WA_JS_URL=$(cat wa-logs.txt | perl -n -e'/Found source JS URL\: (.+)/ && print $1')
          echo "wa_version=$WA_VERSION" >> $GITHUB_OUTPUT
          echo "wa_js_url=$WA_JS_URL" >> $GITHUB_OUTPUT

      - name: GenerateStatics
        run: |
          export PATH="$(yarn bin):$PATH"
          sh WAProto/GenerateStatics.sh  # Use sh to run the script

      - name: Update baileys-version.json
        run: |
          WA_VERSION="${{steps.wa_proto_info.outputs.wa_version}}"
          WA_NUMBERS=$(echo $WA_VERSION | sed "s/\./, /g")
          echo -e "{\n\t\"version\": [$WA_NUMBERS]\n}" > src/Defaults/baileys-version.json
